---
title: "Fig1 Panels"
output: html_notebook
---

# Dependencies
```{r}
library(Seurat)
library(tidyverse)
library(ggrastr)
options(ggrastr.default.dpi=600)
```

# Load common data
```{r}
seurat <- readRDS("../../../data/pan_cancer_epi.rds")
meta_list <- readRDS("../../../output/master_metadata.rds")
```

# Fig 1A - Pan-cancer UMAP

```{r}
dat <- seurat@meta.data
dat$Group <- paste0(dat$Cancer, "_", dat$Source)
dat$UMAP1 <- Embeddings(seurat, 'umap')[,1]
dat$UMAP2 <- Embeddings(seurat, 'umap')[,2]
```

```{r}
cols <- c("#ebac23", "#b80058", "#008cf9", "#006e00", "#00bbad", "#d163e6", "#b24502", "#ff9287")
cancer_plot <- ggplot(dat, aes(UMAP1, UMAP2)) +
  geom_point_rast(size=0.01, shape=16, alpha=0.75, aes(color=Cancer)) +
  scale_colour_manual(values=cols) +
  guides(colour = guide_legend(override.aes = list(size=4))) +
  theme_void() +
  theme(legend.title=element_blank(),
        legend.text = element_text(size=12))
cancer_plot
```

```{r}
ggsave(cancer_plot, filename="pan_cancer_umap.pdf", 
       width=5, height=3.25)
```

And just to get the counts of cells/samples per cancer type

```{r}
seurat@meta.data %>%
  group_by(Cancer) %>%
  summarise(count = n())
```

```{r}
seurat@meta.data %>%
  select(Cancer, SampleID) %>%
  group_by(Cancer) %>%
  summarise(count = length(unique(SampleID)))
```


# Fig 1B
## Arch PCA
Colorectal Lee KUL01 is a decent one to do for this schematic

```{r}
sampleID <- "Colorectal_Lee_KUL01"
cells <- rownames(meta_list[[sampleID]])
seurat_subset <- subset(seurat, cells = cells)
seurat_subset <- SCTransform(seurat_subset, vars.to.regress="percent.mito")
seurat_subset <- RunPCA(seurat_subset, verbose=F)

dat <- meta_list[[sampleID]]
dat$PC1 <- Embeddings(seurat_subset, "pca")[,1]
dat$PC2 <- Embeddings(seurat_subset, "pca")[,2]
dat$A1 <- dat$A1 / max(dat$A1)
dat$A2 <- dat$A2 / max(dat$A2)
dat$A3 <- dat$A3 / max(dat$A3)
dat$A4 <- dat$A4 / max(dat$A4)
```

```{r}
pca_no_color <- ggplot(dat, aes(PC1, PC2)) +
    geom_point(size=1, shape=16, color="grey", alpha=0.8) +
    theme_classic() +
    theme(axis.text=element_text(size=10, color="black"),
          axis.title=element_text(size=12),
          legend.title=element_text(size=12),
          legend.text=element_text(size=12))
```

```{r}
df <- dat %>%
  select(PC1, PC2, A1, A2, A3, A4) %>%
  pivot_longer(cols = -c(PC1, PC2),
               names_to = "Program",
               values_to = "Score")
```

```{r}
pca_programs <- ggplot(df, aes(PC1, PC2)) +
  geom_point(size=0.5, shape=16, aes(color=Score)) +
  scale_color_gradientn(colors=viridis::mako(100), #colours = c("lightgrey", "red"),
                        name="Program\nscore",
                        guide = guide_colorbar(ticks.colour = "black",
                                              frame.colour = "black",
                                              barwidth=0.75)) +
  facet_wrap(~Program, ncol =2) +
  theme_bw() +
  theme(axis.text=element_blank(),#element_text(size=10, color="black"),
        axis.title=element_blank(),#element_text(size=12),
        axis.ticks=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title=element_text(size=12),
        legend.text=element_text(size=12),
        strip.background = element_blank(),
        strip.text = element_text(size=12, color="black"),
        panel.border = element_rect(size=0.5))
pca_programs
```

```{r}
ggsave(pca_programs, filename="kul01_activity.pdf",
       width=4, height=2.75)

ggsave(pca_no_color, filename="kul01_pca_nocolor.pdf",
       width=3, height=2.5)
```

```{r}
kul01 <- cowplot::plot_grid(pca_no_color, pca_programs, ncol=2,
                   align="h", axis="tb",
                   rel_widths = c(1,1.25))
```

```{r}
cowplot::save_plot(kul01,
                   filename="kul_pca.pdf",
                   base_width = 5.5, base_height=2.5)
```



```{r}
plotArch_PCA <- function(sampleID){
  print(paste0("Processing sample: ", sampleID))
  cells <- rownames(meta_list[[sampleID]])
  seurat_subset <- subset(seurat, cells = cells)
  seurat_subset <- SCTransform(seurat_subset, vars.to.regress="percent.mito")
  seurat_subset <- RunPCA(seurat_subset, verbose=F)
  
  dat <- meta_list[[sampleID]]
  dat$PC1 <- Embeddings(seurat_subset, "pca")[,1]
  dat$PC2 <- Embeddings(seurat_subset, "pca")[,2]
  
  #Get specific cell for each archetype
  dat$Archetype_Membership <- paste0("A", dat$Archetype_Membership)
  archs <- unique(dat$Archetype_Membership)
  arch_dat <- dat[,c("Archetype_Membership", archs)]
  arch_dat$Cell <- rownames(dat)
  arch_dat <- arch_dat %>% 
    pivot_longer(!c(Archetype_Membership, Cell), 
                 names_to = "Archetype",
                 values_to = "Score") %>%
    group_by(Archetype) %>%
    filter(Score == max(Score))
  arch_dat$PC1 <- dat[arch_dat$Cell, "PC1"]
  arch_dat$PC2 <- dat[arch_dat$Cell, "PC2"]
  
  
  pca_plot <- ggplot(dat, aes(PC1, PC2)) +
    geom_point(size=1, shape=16, aes(color=Archetype_Membership), alpha=0.5) +
    geom_point(data=arch_dat, aes(fill=Archetype_Membership), shape=21, 
               colour="black", size=4) +
    scale_color_brewer(palette="Dark2") +
    scale_fill_brewer(palette="Dark2") +
    theme_classic() +
    theme(axis.text=element_text(size=10, color="black"),
          axis.title=element_text(size=12),
          legend.title=element_text(size=12),
          legend.text=element_text(size=12))
  
  pca_no_color <- ggplot(dat, aes(PC1, PC2)) +
    geom_point(size=1, shape=16, color="grey", alpha=0.5) +
    theme_classic() +
    theme(axis.text=element_text(size=10, color="black"),
          axis.title=element_text(size=12),
          legend.title=element_text(size=12),
          legend.text=element_text(size=12))
  
  ggsave(pca_plot, filename= paste0(sampleID,  "_arch_membership.pdf"),
         width=3, height=2.5)
  
}

plotArch_PCA("Colorectal_Lee_KUL01")

```

## Correlation w/ EMT
```{r}
emt_names <- c("Taube", "Tan_EMT", "GO", "CancerSEA", "Kinker_II", "Kinker_III",
                    "Hallmark", "Puram_pEMT", "dbEMT", "Cook", "Kinker_I")
```


```{r}
getCor <- function(df){
  total_arch <- unique(paste0("A", unique(df$Archetype_Membership)))
  total_arch <- total_arch[order(total_arch)]
  cor_mat <- cor(df[,total_arch], df[,emt_names])
}

cor_dat <- getCor(meta_list[["Colorectal_Lee_KUL01"]])
```

```{r}
gene_set_order <- c("Taube", "Tan_EMT", "GO", "CancerSEA", "Kinker_II", "Kinker_III",
                    "Hallmark", "Puram_pEMT", "dbEMT", "Cook", "Kinker_I")
pheatmap::pheatmap(t(cor_dat[,gene_set_order]),
         color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(100),
         breaks = seq(-0.75, 0.75, length.out=101),
         border_col="black",
         cluster_rows = F,
         cluster_cols = F,
         clustering_method="ward.D2",
         filename = "kul01_emt_cor.pdf",
         width=2.5, height=2.4)
```

# Fig 1C
## Heatmap of Ovarian
```{r}
emt_sets <- c("Taube", "Tan_EMT", "GO", "CancerSEA", "Kinker_II", "Kinker_III",
                    "Hallmark", "Puram_pEMT", "dbEMT", "Cook", "Kinker_I")
getCor <- function(df){
  total_arch <- unique(paste0("A", unique(df$Archetype_Membership)))
  total_arch <- total_arch[order(total_arch)]
  cor_mat <- cor(df[,total_arch], df[,emt_sets])
}

cor_list <- lapply(meta_list, getCor)
```

```{r}
annotation <- unique(seurat@meta.data[,c("Source", "Cancer", "SampleID")])
annotation$Source <- paste0(annotation$Source, "_", annotation$Cancer)
unique_source <- unique(annotation$Source)
```

```{r}
all_heatmaps <- list()
for(i in 1:length(unique_source)){
  samples <- annotation %>% filter(Source == unique_source[i]) %>% pull(SampleID)
  
  heat_list <- NULL
  for(n in 1:length(samples)){
    cols <- colorRampPalette(rev(brewer.pal(n = 9, name = "RdBu")))(5)
    col_fun = circlize::colorRamp2(c(-0.75, -0.25, 0, 0.25, 0.75), cols)
    #lgd = Legend(col_fun = col_fun, title = "Pearson\ncorrelation", border = "black")
    heat <- Heatmap(t(cor_list[[samples[n]]])[gene_set_order,], 
                  name=samples[n],
                  column_title = word(samples[n], start=3, end=-1, sep="_"),
                  column_title_gp = gpar(fontsize = 8),
                  col=col_fun,
                  rect_gp = gpar(col = "black", lwd = 1),
                  show_column_dend = FALSE,
                  cluster_rows = F,
                  show_heatmap_legend=F)
                  #heatmap_legend_param = list(col_fun = col_fun, 
                   #                           title = "Pearson\ncorrelation", 
                    #                          border = "black",
                     #                         title_gp = gpar(col = "black", fontsize = 12)))
    
    heat_list <- heat_list + heat
  }
  all_heatmaps[[i]] <- heat_list
}
```

```{r}
unique_source #order of all_heatmaps
```


```{r}
pdf(file = "archetype_emt_correlation_Geistlinger_Ovarian.pdf",
    width=5, height=2.75)
all_heatmaps[[10]]
dev.off()
```


## All programs
```{r}
cor_list_merge <- read.csv("../../../output/archetype_emt_correlation.csv", row.names=1)
cor_list_merge <- as.matrix(cor_list_merge)
```

```{r}
#cols <- paletteer::paletteer_c("scico::berlin", n=100)
cols <- colorRampPalette(rev(RColorBrewer::brewer.pal(9, "RdBu")))(100)
```

```{r}
emt_cor_heatmap <- pheatmap::pheatmap(t(cor_list_merge[,gene_set_order]),
                                      color = cols,
                                      breaks=seq(-0.75, 0.75, length.out=101),
                                      cluster_rows=F,
                                      cluster_cols=T,
                                      treeheight_col = 15,
                                      show_colnames=F,
                                      legend=F,
                                      cutree_col=2,
                                      fontsize = 12,
                                      angle_col=45,
                                      clustering_method="ward.D2",
                                      filename="archetype_emt_correlation_all.pdf",
                                      width=6.2, height=2.2)
```
