---
title: "Figure S3 Panels"
output: html_notebook
---

```{r}
library(Seurat)
library(tidyverse)
library(ggridges)
```

# Load the data
```{r}
seurat <- readRDS("../../data/pan_cancer_epi.rds")
meta_list <- readRDS("../../output/master_metadata.rds")
meta_list <- do.call("bind_rows", meta_list)
```

```{r}
dat <- seurat@meta.data
dat$Group <- paste0(dat$Cancer, " - ", dat$Source)
dat$SampleFull <- paste0(dat$Cancer, "_", dat$Patient)
dat <- dat %>% arrange(Group)
dat$SampleFull <- factor(dat$SampleFull, levels=unique(dat$SampleFull))

row_idx <- match(rownames(dat), rownames(meta_list))
dat$Hallmark <- meta_list$Hallmark[row_idx]
dat$Puram_pEMT <- meta_list$Puram_pEMT[row_idx]
dat$Cook <- meta_list$Cook[row_idx]
```


# Fig S4A - Ridgeplot of EMT Signature
```{r}
emt_sig_plot <- ggplot(dat, aes(x=EMT_Sig, y=SampleFull)) +
  geom_density_ridges(aes(fill=Group), color="black", scale=2.5, alpha=0.5) +
  ylab("") + xlab("Gene set score") +
  ggtitle("Conserved EMP Genes") +
  theme_ridges() +
  theme(axis.text.y=element_text(size=6),
        axis.text.x=element_text(size=12, color="black"),
        axis.title = element_text(size=12),
        plot.title = element_text(size=12, face="plain"),
        legend.position="none")
```


# Fig S4B - Ridgeplot of EMT Gene sets

```{r}
hallmark_plot <- ggplot(dat, aes(x=Hallmark, y=SampleFull)) +
  geom_density_ridges(aes(fill=Group), color="black", scale=2.5, alpha=0.5) +
  ylab("") + xlab("Gene set score") +
  ggtitle("MSigDB Hallmark") +
  theme_ridges() +
  theme(axis.text.y=element_blank(),
        axis.text.x=element_text(size=12, color="black"),
        axis.title = element_text(size=12),
        plot.title = element_text(size=12, face="plain"),
        legend.position = "none")
```

```{r}
puram_plot <- ggplot(dat, aes(x=Puram_pEMT, y=SampleFull)) +
  geom_density_ridges(aes(fill=Group), color="black", scale=2.5, alpha=0.5) +
  ylab("") + xlab("Gene set score") +
  ggtitle("Puram pEMT") +
  theme_ridges() +
  theme(axis.text.y=element_blank(),
        axis.text.x=element_text(size=12, color="black"),
        axis.title = element_text(size=12),
        plot.title = element_text(size=12, face="plain"),
        legend.position = "none")
```

```{r}
cook_plot <- ggplot(dat, aes(x=Puram_pEMT, y=SampleFull)) +
  geom_density_ridges(aes(fill=Group), color="black", scale=2.5, alpha=0.5) +
  ylab("") + xlab("Gene set score") +
  ggtitle("Cook EMT Signature") +
  theme_ridges() +
  theme(axis.text.y=element_blank(),
        axis.text.x=element_text(size=12, color="black"),
        axis.title = element_text(size=12),
        plot.title = element_text(size=12, face="plain"),
        legend.title=element_blank())
```

# Plot all
```{r}
all_plots <- cowplot::plot_grid(emt_sig_plot, hallmark_plot, puram_plot, cook_plot,
                                ncol=4, align="h", rel_widths = c(0.7,0.5,0.5,1.05))

cowplot::save_plot(all_plots, filename="signature_scores.pdf",
          base_width=14, base_height=15)
```




